# Generated by Django 2.1.7 on 2019-03-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event name')),
                ('date', models.DateTimeField(verbose_name='Event date')),
                ('reminder', models.CharField(blank=True, choices=[('1h', 'remind for 1 hour'), ('2h', 'remind for 2 hours'), ('4h', 'remind for 4 hours'), ('1d', 'remind for 1 day'), ('1w', 'remind for a week')], max_length=255, null=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True, verbose_name='Reminder date')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
