# Generated by Django 2.1.7 on 2019-03-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reminder',
            field=models.CharField(blank=True, choices=[('1h', 'remind for 1 hour'), ('2h', 'remind for 2 hours'), ('4h', 'remind for 4 hours'), ('1d', 'remind for 1 day'), ('1w', 'remind for a week')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
