# Generated by Django 2.1.7 on 2019-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190312_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reminder date'),
        ),
    ]
