# Generated by Django 2.1.7 on 2019-03-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start event date'),
        ),
        migrations.AddField(
            model_name='event',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stop event date'),
        ),
    ]
